#!/usr/bin/env python3

from sys import argv, exit

from src.error_arg import check_error
from src.usage import display_usage
from src.intersection import (
    intersection_sphere,
    intersection_cone,
    intersection_cylinder,
)


def check_option(av: list[str]) -> int:
    if int(av[1]) == 1:
        print(f"Sphere of radius {av[8]}")
        print(
            f"Line passing through the point ({av[2]}, {av[3]}, {av[4]}) and parallel to the vector ({av[5]}, {av[6]}, {av[7]})"
        )
        intersection_sphere(av)
    elif int(av[1]) == 2:
        print(f"Cylinder of radius {av[8]}")
        print(
            f"Line passing through the point ({av[2]}, {av[3]}, {av[4]}) and parallel to the vector ({av[5]}, {av[6]}, {av[7]})"
        )
        intersection_cylinder(av)
    elif int(av[1]) == 3:
        print(f"Cone with a {av[8]} degree angle")
        print(
            f"Line passing through the point ({av[2]}, {av[3]}, {av[4]}) and parallel to the vector ({av[5]}, {av[6]}, {av[7]})"
        )
        intersection_cone(av)
    else:
        print("Error : option is unknown: retry with -h")
        return 84
    return 0


def main() -> int:
    if "-h" in argv:
        display_usage()
        return 0
    if check_error(argv) == 84:
        return 84
    return check_option(argv)


if __name__ == "__main__":
    exit(main())
